create table if not exists tag 
(
    id int generated by default as identity,
    tag varchar(100) not null,
    feedback_id int not null,
    primary key(id),
    constraint fk_feedback 
        foreign key(feedback_id) 
        references feedback(id)
);